### ISSUE TITLE
Odd Dterm spectrogram for unfiltered vs filtered, below 100Hz

### ISSUE THREAD

**Issue by ysoldak** [bw1129/PIDtoolbox#12]
Most likely I'm missing something, so consider this more like request for comment or tip for a topic in the documentation.

When comparing Dterm (unfilt) vs Dterm with "<100Hz" checkboxes checked, I see both peak and mean are larger on "filtered" graph compared to "unfiltered". Filtered indeed looks worse overall too. How shall I interpret this? Is this due to normalisation? Why this does not happened for Gyro spectrograms?

A bonus question on Dterm data, if I may...
Where Dterm unfiltered data comes from? I have debug set to "GYRO_SCALED", does it log Dterm too? Can't see that debug field in Betaflight Blackbox Explorer...

<img width="675" alt="Odd_Dterm_spectrogram" src="https://user-images.githubusercontent.com/1061565/57253473-15ae9100-704f-11e9-91ea-276a4ceffe41.png">

[1306_4.BBL.zip](https://github.com/bw1129/PIDtoolbox/files/3149740/1306_4.BBL.zip)

**Comment by bw1129** [comment]
There is an issue I have to resolve with respect to scaling unfiltered dterm to match scale of original. Basically, filtered dterm is computed by Betaflight, and I compute unfiltered dterm by taking the first dirivative of gyro. But this alone does not result in properly scaled unfiltered dterm. Currently I do a sort of normalization but need to use the current D setting implemented by the user. Should be fixed in next version. Thx
