### ISSUE TITLE
Feature Request: Highlight differences in setup info page

### ISSUE THREAD

**Issue by psim** [bw1129/PIDtoolbox#23]
Very useful to catch differences in a quick way.

Thanks

**Comment by bw1129** [comment]
so I have been looking into this and it turns out to be far more difficult to do that one might imagine. The problem arises when making comparisons between different versions of BF as the list of variables may change, not just the names, but number of entries etc. If you know anything about programming it's a case of "string hell". I'm gonna have to pass on this for now. as such, I will close this feature request for the time being.
