### ISSUE TITLE
Error in PTload

### ISSUE THREAD

**Issue by AndreySemjonov** [bw1129/PIDtoolbox#58]
For EmuFlight logs on latest 0.42 PIDtoolbox getting error
![image](https://user-images.githubusercontent.com/50518855/123239164-c5714200-d4e7-11eb-8f01-44150fa982bb.png)
Do not have same issue with 0.392

Here log:
[8.zip](https://github.com/bw1129/PIDtoolbox/files/6708055/8.zip)

If this is issue on EMUF side than we can fix it.

**Comment by bw1129** [comment]
I see the error. Dmin and FF strings empty. Fixed and will be part of next release. 
![PTB_FIGS_EMUlogWontWorkPTB0 42xx_24-Jun-2021-1](https://user-images.githubusercontent.com/17284912/123259395-68af6080-d4c2-11eb-859f-b9c3917a4545.png)

**Comment by bw1129** [comment]
ah, here's a version with the fix. Go ahead and try this one. 
https://www.dropbox.com/s/n2njf6ys47g5fky/main.zip?dl=0

**Comment by AndreySemjonov** [comment]
Thanks. It is OK now

**Comment by bw1129** [comment]
Excellent!

Keep this 'issue' here so others can download the fix if needed.

**Comment by massimilianodossi** [comment]
hi , can you provide the corrected file for MAC also ?

**Comment by bw1129** [comment]
No prob. I’ll post it here in a bit. New release in the works as well soon

**Comment by bw1129** [comment]
emu fix for mac users. you also get a few extra fixes for free with this version ;-)
https://www.dropbox.com/s/d357g4klnhe5wyy/main_forMac.zip?dl=0

**Comment by massimilianodossi** [comment]
sorry but the ptload error persist

**Comment by bw1129** [comment]
I just ran it using the emu log posted above and it works fine. you must have a different issue. normally this doesnt matter, but delete the old PIDtoolbox.app then try the logfile above (linked in the first post at beginning of this issue)

**Comment by charlesmarseille** [comment]
while trying to open an iNAV log, I get a new error (was getting the one posted above before):
Error in PTload
unrecognized variable name 'setpoint_0_'.

So I guess you fixed the variable names, but not for the "special" iNAV ones. maybe a simple fix?

**Comment by bw1129** [comment]
PTB 0.4+ went through complete overhaul. The file importing functions had to be rewritten to accommodate the new multi-file structure. As a result I had to make a decision how complicated I wanted it to be and I opted for a very simplified approach. Compare PTload and PTimport now compared to v0.392 for example. So I don’t rename anything now. It comes is as Blackbox_decode exports it and that’s all determined by the main firmware developer. Both BF and EMU use the same basic variable names for set point etc, but INAV doesn’t. So given the small INAV user base I decided to stop support for INAV. I made a post in INAV asking who uses PTB and got like 3-4 responses. PTB v0.392 still works for INAV users so that’s where I left it. If more INAV users expressed interest I’d work at it.

**Comment by charlesmarseille** [comment]
Yes, I saw your ask for the interest in iNAV users, not so many responses. I then tried 0.392, and got the same error. Just by changing these 2 header variables I got it working though.
Thanks for your great work, really enjoy that visualisation of the data.

**Comment by Quick-Flash** [comment]
Hey whatever it takes to help you keep supporting emu we would be happy to help.

**Comment by bw1129** [comment]
Hey thanks Kevin! So far so good. I think as long as the main variable names come out of bb_decode the same we’re generally good to go.
